language: php

php:
  - 7.1
  - 7.2
  - 7.3

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist
  #- composer config process-timeout 2000
  #- export COMPOSER_PROCESS_TIMEOUT=2000
  - cd $TRAVIS_BUILD_DIR

script:
  - composer lint
  - composer install-cs-fixer
  - composer check-style
  - composer phpstan
  - composer test-coverage

